apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: lab-debug
spec:
  portal:
    registration:
      type: anonymous
  workshops:
  - name: lab-debug
    capacity: 1
    expires: 120m
    orphaned: 120m
