apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: lab-debug
spec:
  analytics:
    webhook:
      url: https://rest-receiver.herokuapp.com/?client=name&token=password
  portal:
    registration:
      type: anonymous
  workshops:
  - name: lab-debug
    capacity: 1
    expires: 120m
    orphaned: 120m
