apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-debug
spec:
  title: Markdown Sample
  description: A basic lab to debug various Educates features
  vendor: eduk8s.io
  difficulty: beginner
  duration: 120m
  url: https://github.com/BrianMMcClain/educates-lab-debug
  content:
    #image: quay.io/eduk8s/lab-markdown-sample:master
    files: github.com/BrianMMcClain/educates-lab-debug
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
